[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'mkdir -p storage/logs storage/framework/sessions storage/framework/views storage/framework/cache bootstrap/cache database',
    'touch database/database.sqlite',
    'chmod -R 777 storage bootstrap/cache database',
    'php artisan migrate --force || echo "Migration failed"',
    'php artisan db:seed --class=HealthPatternsSeeder --force || echo "Seeding failed"'
]

[start]
cmd = 'php artisan serve --host=0.0.0.0 --port=$PORT'
